name: "Generate android version based on time"
description: "This action will update the version code directly in build.gradle . "
inputs:
  gradlePath:
    description: "Gradle path to override version"
    required: true
    default: "app/build.gradle"
  versionName:
    description: "The new version name"
    required: false
outputs:
  result: # id of output
    description: "Action Result"
runs:
  using: "node12"
  main: "index.js"
branding:
  color: 'blue'
  icon: 'anchor'
